id = "janet"
name = "Janet"
description = "Janet language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Marek Stefanka <marekstefanka@duck.com>"]
repository = "https://github.com/flajr/zed-janet"

[grammars.janet]
repository = "https://github.com/GrayJack/tree-sitter-janet"
commit = "main"

[language_servers.janet-lsp]
name = "janet-lsp"
language = "Janet"
