id = "janet"
name = "Janet"
description = "Janet language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Marek Stefanka <marekstefanka@duck.com>"]
repository = "https://github.com/flajr/janet-zed"

[grammars.janet]
repository = "https://github.com/GrayJack/tree-sitter-janet"
commit = "1d002c23d4e952ce24a2e472d0f81ab0471ceb1b"

[language_servers.janet-lsp]
name = "janet-lsp"
language = "Janet"
