id = "janet"
name = "Janet"
description = "Janet language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Marek Stefanka <marekstefanka@duck.com>"]
repository = "https://github.com/flajr/janet-zed"

[grammars.janet]
repository = "https://github.com/flajr/tree-sitter-janet"
rev = "main"

[language_servers.janet-lsp]
name = "janet-lsp"
language = "Janet"
